Dependencies:
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'third-party/wayland': '@latest'

Options:
  test-before-installing: True
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
